import { Product } from '../models/product.model';

export const MOCK_PRODUCTS: Product[] = [
  // ── Electronics ──────────────────────────────────────────────────────────
  {
    id: 'prod_001',
    slug: 'headtorch-vertex-pro',
    name: 'Headtorch Vertex Pro',
    brand: 'Sonix',
    category: 'electronics',
    description:
      'Top of the line rechargeable LED headtorch. 2000 lumens, 150m beam distance, and a battery life of up to 100 hours on low mode. USB-C charging and a waterproof IPX6 rating.',
    price: 349.99,
    compareAtPrice: 420,
    currency: 'GBP',
    images: [
      { id: 'img_001a', url: 'images/Fenix-HM65R-Rechargeable-LED-Head-Torch.jpg', alt: 'Headtorch Vertex Pro front', isPrimary: true },
      { id: 'img_001b', url: 'https://placehold.co/600x600/2a2a2a/ffffff?text=Vertex+Side', alt: 'Headtorch Vertex Pro side', isPrimary: false },
    ],
    variants: [
      { id: 'var_001a', label: 'Color', value: 'Midnight Black', stock: 12, priceDelta: 10 },
      { id: 'var_001b', label: 'Color', value: 'Arctic White', stock: 5, priceDelta: 0 },
      { id: 'var_001c', label: 'Color', value: 'Deep Navy', stock: 0, priceDelta: 0 },
    ],
    tags: ['noise-cancelling', 'wireless', 'studio'],
    rating: 4.8,
    reviewCount: 342,
    stock: 17,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-09-12T00:00:00Z',
  },
  {
    id: 'prod_002',
    slug: 'lumos-smart-watch-x3',
    name: 'Lumos Watch X3',
    brand: 'Lumos',
    category: 'electronics',
    description:
      'Precision health tracking meets refined design. ECG, SpO2, sleep analysis, and a gorgeous AMOLED display housed in aerospace-grade aluminium. Water resistant to 50m.',
    price: 299.99,
    currency: 'GBP',
    images: [
      { id: 'img_002a', url: 'https://placehold.co/600x600/0f2027/ffffff?text=Lumos+X3', alt: 'Lumos Watch X3', isPrimary: true },
    ],
    variants: [
      { id: 'var_002a', label: 'Case Size', value: '41mm', stock: 1, priceDelta: 0 },
      { id: 'var_002b', label: 'Case Size', value: '45mm', stock: 2, priceDelta: 30 },
    ],
    tags: ['smartwatch', 'health', 'fitness'],
    rating: 4.6,
    reviewCount: 218,
    stock: 3,
    isFeatured: false,
    isNew: true,
    createdAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'prod_003',
    slug: 'xtorm-solarbooster',
    name: 'Xtorm SolarBooster 28V',
    brand: 'Xtorm',
    category: 'electronics',
    description:
      'High-efficiency portable solar charger with a 20,000mAh battery. Dual USB-C ports, foldable solar panels, and a rugged IP67 waterproof design. Perfect for off-grid adventures.',
    price: 179,
    currency: 'GBP',
    images: [
      { id: 'img_003a', url: 'https://placehold.co/600x600/1c1c1e/e5e5e5?text=Xtorm+SolarBooster+28V', alt: 'Xtorm SolarBooster', isPrimary: true },
    ],
    variants: [
      { id: 'var_003a', label: 'Color', value: 'Black', stock: 15, priceDelta: 0 },
      { id: 'var_003b', label: 'Color', value: 'Silver', stock: 10, priceDelta: 0 },
      { id: 'var_003c', label: 'Color', value: 'Blue', stock: 7, priceDelta: 0 },
    ],
    tags: ['solar', 'charger', 'portable', 'waterproof'],
    rating: 4.9,
    reviewCount: 87,
    stock: 32,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-11-20T00:00:00Z',
  },

  // ── Apparel ───────────────────────────────────────────────────────────────
  {
    id: 'prod_004',
    slug: 'atlas-merino-crew',
    name: 'Atlas Merino Crew',
    brand: 'Greyfields',
    category: 'apparel',
    description:
      'A premium 100% Merino wool crewneck. Naturally temperature-regulating, odour-resistant, and incredibly soft. Cut slightly relaxed for layering without bulk.',
    price: 98,
    currency: 'GBP',
    images: [
      { id: 'img_004a', url: 'https://placehold.co/600x600/4a4a4a/f0f0f0?text=Atlas+Merino', alt: 'Atlas Merino Crew', isPrimary: true },
    ],
    variants: [
      { id: 'var_004a', label: 'Size', value: 'XS', stock: 4, priceDelta: 0 },
      { id: 'var_004b', label: 'Size', value: 'S', stock: 9, priceDelta: 0 },
      { id: 'var_004c', label: 'Size', value: 'M', stock: 12, priceDelta: 0 },
      { id: 'var_004d', label: 'Size', value: 'L', stock: 8, priceDelta: 0 },
      { id: 'var_004e', label: 'Size', value: 'XL', stock: 5, priceDelta: 0 },
    ],
    tags: ['merino', 'knitwear', 'essentials'],
    rating: 4.7,
    reviewCount: 156,
    stock: 38,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-08-01T00:00:00Z',
  },
  {
    id: 'prod_005',
    slug: 'cloud-tech-jogger',
    name: 'Cloud Tech Jogger',
    brand: 'Kinetic',
    category: 'apparel',
    description:
      'Four-way stretch performance jogger crafted from recycled polyester blend. Tapered fit, hidden phone pocket, reflective piping, and a waistband that stays put.',
    price: 72,
    currency: 'GBP',
    images: [
      { id: 'img_005a', url: 'https://placehold.co/600x600/2d3142/ffffff?text=Cloud+Jogger', alt: 'Cloud Tech Jogger', isPrimary: true },
    ],
    variants: [
      { id: 'var_005a', label: 'Size', value: 'S', stock: 6, priceDelta: 0 },
      { id: 'var_005b', label: 'Size', value: 'M', stock: 14, priceDelta: 0 },
      { id: 'var_005c', label: 'Size', value: 'L', stock: 10, priceDelta: 0 },
      { id: 'var_005d', label: 'Size', value: 'XL', stock: 4, priceDelta: 0 },
    ],
    tags: ['joggers', 'activewear', 'sustainable'],
    rating: 4.4,
    reviewCount: 93,
    stock: 34,
    isFeatured: false,
    isNew: true,
    createdAt: '2025-02-14T00:00:00Z',
  },

  // ── Footwear ──────────────────────────────────────────────────────────────
  {
    id: 'prod_006',
    slug: 'ridge-trail-runner',
    name: 'Ridge Trail Runner',
    brand: 'Apex',
    category: 'footwear',
    description:
      'Lightweight trail running shoe built for technical terrain. Vibram® MegaGrip outsole, dynamic lacing system, and a rock-plate midsole that protects without sacrificing ground feel.',
    price: 145,
    compareAtPrice: 175,
    currency: 'GBP',
    images: [
      { id: 'img_006a', url: 'https://placehold.co/600x600/3d5a3e/f5f5f5?text=Ridge+Trail', alt: 'Ridge Trail Runner', isPrimary: true },
    ],
    variants: [
      { id: 'var_006a', label: 'UK Size', value: '7', stock: 3, priceDelta: 0 },
      { id: 'var_006b', label: 'UK Size', value: '8', stock: 5, priceDelta: 0 },
      { id: 'var_006c', label: 'UK Size', value: '9', stock: 8, priceDelta: 0 },
      { id: 'var_006d', label: 'UK Size', value: '10', stock: 6, priceDelta: 0 },
      { id: 'var_006e', label: 'UK Size', value: '11', stock: 4, priceDelta: 0 },
      { id: 'var_006f', label: 'UK Size', value: '12', stock: 2, priceDelta: 0 },
    ],
    tags: ['trail', 'running', 'vibram', 'outdoors'],
    rating: 4.8,
    reviewCount: 204,
    stock: 28,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-07-22T00:00:00Z',
  },
  {
    id: 'prod_007',
    slug: 'sunday-canvas-low',
    name: 'Sunday Canvas Low',
    brand: 'Fieldstone',
    category: 'footwear',
    description:
      'The everyday sneaker, refined. Hand-crafted from organic canvas with a vulcanised rubber sole and a memory foam insole. Gets better with every wear.',
    price: 89,
    currency: 'GBP',
    images: [
      { id: 'img_007a', url: 'https://placehold.co/600x600/f0ebe3/2a2a2a?text=Sunday+Low', alt: 'Sunday Canvas Low', isPrimary: true },
    ],
    variants: [
      { id: 'var_007a', label: 'UK Size', value: '6', stock: 4, priceDelta: 0 },
      { id: 'var_007b', label: 'UK Size', value: '7', stock: 7, priceDelta: 0 },
      { id: 'var_007c', label: 'UK Size', value: '8', stock: 10, priceDelta: 0 },
      { id: 'var_007d', label: 'UK Size', value: '9', stock: 8, priceDelta: 0 },
      { id: 'var_007e', label: 'UK Size', value: '10', stock: 5, priceDelta: 0 },
    ],
    tags: ['canvas', 'casual', 'everyday'],
    rating: 4.5,
    reviewCount: 311,
    stock: 34,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-03-10T00:00:00Z',
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    id: 'prod_008',
    slug: 'porter-leather-wallet',
    name: 'Porter Slim Wallet',
    brand: 'Porter',
    category: 'accessories',
    description:
      'Full-grain vegetable-tanned leather bifold that slims down to 8mm. Holds 6 cards and cash. Develops a gorgeous patina with age.',
    price: 58,
    currency: 'GBP',
    images: [
      { id: 'img_008a', url: 'https://placehold.co/600x600/6b4226/f5e6d3?text=Porter+Wallet', alt: 'Porter Slim Wallet', isPrimary: true },
    ],
    variants: [
      { id: 'var_008a', label: 'Color', value: 'Tan', stock: 20, priceDelta: 0 },
      { id: 'var_008b', label: 'Color', value: 'Dark Brown', stock: 15, priceDelta: 0 },
      { id: 'var_008c', label: 'Color', value: 'Black', stock: 18, priceDelta: 0 },
    ],
    tags: ['leather', 'wallet', 'minimalist'],
    rating: 4.9,
    reviewCount: 528,
    stock: 53,
    isFeatured: false,
    isNew: false,
    createdAt: '2023-11-05T00:00:00Z',
  },
  {
    id: 'prod_009',
    slug: 'drift-20l-daypack',
    name: 'Drift 20L Daypack',
    brand: 'Wanderlite',
    category: 'accessories',
    description:
      'A 20-litre daypack made from 100% recycled 600D ripstop. Padded 15" laptop sleeve, hidden back pocket, and aircraft-grade YKK zippers. Packs flat for travel.',
    price: 124,
    currency: 'GBP',
    images: [
      { id: 'img_009a', url: 'https://placehold.co/600x600/1a2d1f/c8d8c0?text=Drift+Pack', alt: 'Drift 20L Daypack', isPrimary: true },
    ],
    variants: [
      { id: 'var_009a', label: 'Color', value: 'Forest', stock: 9, priceDelta: 0 },
      { id: 'var_009b', label: 'Color', value: 'Slate', stock: 11, priceDelta: 0 },
      { id: 'var_009c', label: 'Color', value: 'Sand', stock: 6, priceDelta: 0 },
    ],
    tags: ['backpack', 'travel', 'sustainable', 'laptop'],
    rating: 4.7,
    reviewCount: 142,
    stock: 26,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-05-18T00:00:00Z',
  },
  {
    id: 'prod_010',
    slug: 'meridian-polarised-sunglasses',
    name: 'Meridian Sunglasses',
    brand: 'Lucent',
    category: 'accessories',
    description:
      'Hand-pressed acetate frames with polarised CR-39 lenses. 100% UV400 protection. Comes with a hand-stitched leather case and microfibre cleaning cloth.',
    price: 135,
    currency: 'GBP',
    images: [
      { id: 'img_010a', url: 'https://placehold.co/600x600/1a1a1a/d4af37?text=Meridian', alt: 'Meridian Sunglasses', isPrimary: true },
    ],
    variants: [
      { id: 'var_010a', label: 'Frame', value: 'Tortoise', stock: 8, priceDelta: 0 },
      { id: 'var_010b', label: 'Frame', value: 'Onyx', stock: 10, priceDelta: 0 },
      { id: 'var_010c', label: 'Frame', value: 'Champagne', stock: 5, priceDelta: 15 },
    ],
    tags: ['sunglasses', 'polarised', 'acetate', 'uv'],
    rating: 4.6,
    reviewCount: 74,
    stock: 23,
    isFeatured: false,
    isNew: true,
    createdAt: '2025-03-01T00:00:00Z',
  },

  // ── Camping ──────────────────────────────────────────────────────────────────
  {
    id: 'prod_011',
    slug: 'bodum-pour-over-set',
    name: 'Kettle Pour Over Set',
    brand: 'Brühen',
    category: 'camping',
    description:
      'A precision gooseneck kettle paired with a borosilicate glass pour-over dripper and stainless steel filter. Heat-resistant handle, variable-temperature control. For the coffee obsessive.',
    price: 88,
    currency: 'GBP',
    images: [
      { id: 'img_011a', url: 'https://placehold.co/600x600/f5f0eb/2a2a2a?text=Pour+Over', alt: 'Kettle Pour Over Set', isPrimary: true },
    ],
    variants: [
      { id: 'var_011a', label: 'Color', value: 'Matte Black', stock: 14, priceDelta: 0 },
      { id: 'var_011b', label: 'Color', value: 'Brushed Steel', stock: 9, priceDelta: 10 },
    ],
    tags: ['coffee', 'kitchen', 'pour-over', 'gift'],
    rating: 4.8,
    reviewCount: 263,
    stock: 23,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-02-14T00:00:00Z',
  },
  {
    id: 'prod_012',
    slug: 'linen-weighted-blanket',
    name: 'Haven Weighted Blanket',
    brand: 'Restwell',
    category: 'camping',
    description:
      'Stone-washed French linen exterior with an inner layer of glass microbeads distributed across 400 individual pockets for even weight distribution. Available in 6kg and 9kg.',
    price: 159,
    currency: 'GBP',
    images: [
      { id: 'img_012a', url: 'images/a3a28878-beb5-41d3-9d44-a47a7ca78bc4.__CR0,0,2000,2000_PT0_SX300_V1___.jpg', alt: 'Haven Weighted Blanket', isPrimary: true },
    ],
    variants: [
      { id: 'var_012a', label: 'Weight', value: '6kg', stock: 11, priceDelta: 0 },
      { id: 'var_012b', label: 'Weight', value: '9kg', stock: 8, priceDelta: 20 },
    ],
    tags: ['blanket', 'sleep', 'linen', 'wellness'],
    rating: 4.7,
    reviewCount: 188,
    stock: 19,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-01-20T00:00:00Z',
  },

  // ── Sports ────────────────────────────────────────────────────────────────
  {
    id: 'prod_013',
    slug: 'kinetic-resistance-bands-set',
    name: 'Kinetic Resistance Band Set',
    brand: 'Kinetic',
    category: 'sports',
    description:
      '5-band set ranging from 5–50lbs resistance. Made from natural latex, colour-coded, with anti-snap guarantee. Includes mesh carry bag, door anchor, and workout guide.',
    price: 44,
    currency: 'GBP',
    images: [
      { id: 'img_013a', url: 'https://placehold.co/600x600/e63946/ffffff?text=Resistance+Bands', alt: 'Kinetic Resistance Band Set', isPrimary: true },
    ],
    variants: [],
    tags: ['resistance', 'gym', 'home-workout', 'latex'],
    rating: 4.5,
    reviewCount: 412,
    stock: 65,
    isFeatured: false,
    isNew: false,
    createdAt: '2024-04-08T00:00:00Z',
  },
  {
    id: 'prod_014',
    slug: 'summit-hydration-vest',
    name: 'Summit Hydration Vest',
    brand: 'Apex',
    category: 'sports',
    description:
      'Ultra-light 8L running vest with dual 500ml soft flasks included. Stretch-woven front pockets, trekking pole loops, and an emergency whistle integrated into the sternum clip.',
    price: 115,
    currency: 'GBP',
    images: [
      { id: 'img_014a', url: 'https://placehold.co/600x600/2b4162/f0f0f0?text=Summit+Vest', alt: 'Summit Hydration Vest', isPrimary: true },
    ],
    variants: [
      { id: 'var_014a', label: 'Size', value: 'XS/S', stock: 6, priceDelta: 0 },
      { id: 'var_014b', label: 'Size', value: 'M/L', stock: 9, priceDelta: 0 },
      { id: 'var_014c', label: 'Size', value: 'XL/XXL', stock: 4, priceDelta: 0 },
    ],
    tags: ['hydration', 'trail-running', 'vest', 'ultra'],
    rating: 4.9,
    reviewCount: 97,
    stock: 19,
    isFeatured: true,
    isNew: false,
    createdAt: '2024-06-30T00:00:00Z',
  },
  {
    id: 'prod_015',
    slug: 'flux-yoga-mat',
    name: 'Flux Natural Rubber Mat',
    brand: 'Flux',
    category: 'sports',
    description:
      '4mm natural rubber yoga mat with alignment markers and a microfibre top layer that grips harder the more you sweat. 183 × 68cm. Comes with a carry strap.',
    price: 79,
    currency: 'GBP',
    images: [
      { id: 'img_015a', url: 'https://placehold.co/600x600/4a7c59/ffffff?text=Flux+Mat', alt: 'Flux Natural Rubber Mat', isPrimary: true },
    ],
    variants: [
      { id: 'var_015a', label: 'Color', value: 'Forest Green', stock: 16, priceDelta: 0 },
      { id: 'var_015b', label: 'Color', value: 'Terracotta', stock: 10, priceDelta: 0 },
      { id: 'var_015c', label: 'Color', value: 'Charcoal', stock: 12, priceDelta: 0 },
    ],
    tags: ['yoga', 'pilates', 'natural-rubber', 'mat'],
    rating: 4.6,
    reviewCount: 231,
    stock: 38,
    isFeatured: false,
    isNew: true,
    createdAt: '2025-01-28T00:00:00Z',
  },
  {
    id: 'prod_016',
    slug: 'apex-folding-bike-helmet',
    name: 'Apex Folding Helmet',
    brand: 'Apex',
    category: 'sports',
    description:
      'The first helmet designed to live in your bag. MIPS-equipped EPS liner folds to half its size in 3 seconds. 22 ventilation channels, magnetic buckle, fits heads 52–62cm.',
    price: 168,
    currency: 'GBP',
    images: [
      { id: 'img_016a', url: 'images/18_CLOSCA_FOLDABLE_HELMET_LOOP_GREEN_AMAZONIA.jpg', alt: 'Apex Folding Helmet', isPrimary: true },
    ],
    variants: [
      { id: 'var_016a', label: 'Color', value: 'Sand', stock: 7, priceDelta: 0 },
      { id: 'var_016b', label: 'Color', value: 'Black', stock: 9, priceDelta: 0 },
      { id: 'var_016c', label: 'Color', value: 'Red', stock: 4, priceDelta: 0 },
    ],
    tags: ['cycling', 'helmet', 'commuter', 'mips', 'folding'],
    rating: 4.7,
    reviewCount: 63,
    stock: 20,
    isFeatured: false,
    isNew: true,
    createdAt: '2025-04-01T00:00:00Z',
  },
];
